//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHINH_GHE
    {
        public string MACG { get; set; }
        public string MAMB { get; set; }
        public string HANGGHE { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual MAYBAY MAYBAY { get; set; }
    }
}
