//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG_HANHKHACH
    {
        public string MAHK { get; set; }
        public string SOGHE { get; set; }
        public string MAGH { get; set; }
        public string MACB { get; set; }
        public string HANGGHE { get; set; }
        public string TENHANHKHACH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public Nullable<int> HANGLY_XACHTAY { get; set; }
        public Nullable<int> HANHLYKYGUI { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual GIOHANG GIOHANG { get; set; }
    }
}
