//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANHLY
    {
        public string MAHL { get; set; }
        public string MAVE { get; set; }
        public string MACB { get; set; }
        public string LOAIHL { get; set; }
        public Nullable<double> KHOILUONG { get; set; }
        public Nullable<double> KICHTHUOC { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual VEMAYBAY VEMAYBAY { get; set; }
    }
}
