//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTRINH
    {
        public string MALT { get; set; }
        public string MACB { get; set; }
        public string SBDI { get; set; }
        public string SBDEN { get; set; }
        public System.DateTime GIOCATCANH { get; set; }
        public System.DateTime GIOHACANH { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
    }
}
