//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETVE
    {
        public string MAVE { get; set; }
        public string MAPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<decimal> GIATIEN { get; set; }
    
        public virtual PHIEUDATVE PHIEUDATVE { get; set; }
        public virtual VEMAYBAY VEMAYBAY { get; set; }
    }
}
