//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG_CHITIET
    {
        public string MAGH { get; set; }
        public string MACB { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> GIATIEN { get; set; }
        public Nullable<System.DateTime> THOIGIANGIU { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual GIOHANG GIOHANG { get; set; }
    }
}
