//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_TRUYCAP
    {
        public int ID { get; set; }
        public string MANV { get; set; }
        public string TENDANGNHAP { get; set; }
        public string THAOTAC { get; set; }
        public string BANGTACTDONG { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string TRANGTHAI { get; set; }
    }
}
