//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYMAYBAYEntities : DbContext
    {
        public QUANLYMAYBAYEntities()
            : base("name=QUANLYMAYBAYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAUHINH_GHE> CAUHINH_GHE { get; set; }
        public virtual DbSet<CHECKIN> CHECKINs { get; set; }
        public virtual DbSet<CHITIETVE> CHITIETVEs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual DbSet<GHE> GHEs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<GIOHANG_CHITIET> GIOHANG_CHITIET { get; set; }
        public virtual DbSet<GIOHANG_HANHKHACH> GIOHANG_HANHKHACH { get; set; }
        public virtual DbSet<HANGGHE_GIA> HANGGHE_GIA { get; set; }
        public virtual DbSet<HANHLY> HANHLies { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOG_TRUYCAP> LOG_TRUYCAP { get; set; }
        public virtual DbSet<LOTRINH> LOTRINHs { get; set; }
        public virtual DbSet<MAYBAY> MAYBAYs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUDATVE> PHIEUDATVEs { get; set; }
        public virtual DbSet<SANBAY> SANBAYs { get; set; }
        public virtual DbSet<THONGKE_DOANHTHU> THONGKE_DOANHTHU { get; set; }
        public virtual DbSet<VEMAYBAY> VEMAYBAYs { get; set; }
    }
}
