//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKIN
    {
        public string MACHECKIN { get; set; }
        public string MAVE { get; set; }
        public string MAKH { get; set; }
        public string MACB { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> THOIGIAN_CHECKIN { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VEMAYBAY VEMAYBAY { get; set; }
    }
}
