//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKE_DOANHTHU
    {
        public string MACB { get; set; }
        public System.DateTime NGAY { get; set; }
        public Nullable<decimal> TONGDOANHTHU { get; set; }
        public Nullable<int> SOLUONGVE { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
    }
}
