//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEMAYBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEMAYBAY()
        {
            this.CHECKINs = new HashSet<CHECKIN>();
            this.CHITIETVEs = new HashSet<CHITIETVE>();
            this.HANHLies = new HashSet<HANHLY>();
        }
    
        public string MAVE { get; set; }
        public string MAGHE { get; set; }
        public string MAHG { get; set; }
        public Nullable<decimal> GIAVE { get; set; }
        public string MACB { get; set; }
        public string MANV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKIN> CHECKINs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETVE> CHITIETVEs { get; set; }
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual GHE GHE { get; set; }
        public virtual HANGGHE_GIA HANGGHE_GIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANHLY> HANHLies { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
